### ISSUE TITLE
X-shooter reductions not initiating

### ISSUE THREAD

**Issue by keheintz** [AWehrhahn/PyReduce#20]
Hi, I downloaded X-shooter data of GRB161023A from the ESO archive, but none of the reduction processes seem to be initiated when I tried running PyReduce (in NIR mode). The python script calling the reduction and the log file is attached here.
Any help appreciated!
[XStest.zip](https://github.com/AWehrhahn/PyReduce/files/5136156/XStest.zip)

**Comment by AWehrhahn** [comment]
Hi, looks like I hardcoded "SHOOT" as the expected instrument name in the fits headers, since thats what I did the tests with.
The latest version on Github should have those problems fixed.

**Comment by AWehrhahn** [comment]
And in all the files for GRB it is called XSHOOTER

**Comment by keheintz** [comment]
Ok thanks, so do I have to install the new version via "python setup.py install"? I installed it previously through pip.

**Comment by AWehrhahn** [comment]
That is one option. Alternatively you can install the latest github version using pip as well: `pip install git+https://github.com/AWehrhahn/PyReduce`

**Comment by keheintz** [comment]
Thanks this worked! However, now it crashes after creating the master flats and biases. The script and log file are attached again. It seems like it crashes with the following error:
Reduction failed with error message: could not broadcast input array from shape (2048) into shape (2106)

[XStest.zip](https://github.com/AWehrhahn/PyReduce/files/5141378/XStest.zip)

**Comment by AWehrhahn** [comment]
I needed to seperate the VIS and NIR branches in the files, this should be working now. I also changed some of the order tracing parameters to make it work better, but it could probably be improved to need less manual input

**Comment by keheintz** [comment]
Thanks it seemed like the reduction went almost flawlessly. Apparently it didn't correctly identify the trace and thus outputs zero flux for most of the NIR order, but I'll see if I can fix it. I can now see that the output spectra are in .ech format -- how should these be read and/or is it possible to output an ascii or fits file with the reduced spectra instead?

**Comment by AWehrhahn** [comment]
I should have fixed the trace problems in the latest update (hopefully).
As for the .ech files, those are just renamed fits files. They can either be read using the echelle class in PyReduce, or any fits reader.
