### ISSUE TITLE
UVES modes

### ISSUE THREAD

**Issue by lisebc** [AWehrhahn/PyReduce#27]
Hi,
Im a complete newbie to PyReduce.

Any reduction chain seems to fail for UVES in different modes : DICHR1, DICHR2.
The code seems to accept "BLUE", "RED", and "MIDDLE".
I wonder if that is an issue, or a bug that can be fixed?

Lise

**Comment by AWehrhahn** [comment]
Its a matter of definition. In PyReduce the modes are defines as "BLUE", "RED", "MIDDLE".

**Comment by lisebc** [comment]
Thank you. 

I though that was the reason why I cannot run a regular UVES reduction chain with a different data set than the example supplied by the PyReduce code.

I am in Copenhagen trying to see what modules we would need to reduce data from NTE as you may already have seen from emails from Johan Fynbo and Kasper Heintz.
In that connection I may have quite a lot of questions, but my first step is simply to understand the PyReduce code.

Best 
Lise
