### ISSUE TITLE
help with lines 

### ISSUE THREAD

**Issue by clrengif** [AWehrhahn/PyReduce#35]
Best regards !!,
I am starting with the topic of spectroscopy and pyreduce and i am starting to configure a new instrument.

Maybe it's an obvious question but I'm a bit confused with ThAr's lamp lines specifically in the creation of the wave_cal file.

I have the lines in this format

1 3600.432
2 3601.034
3 3603.204
4 3604.682
5 3605,194
6 3605.879
7 3606.522
8 3608,378
9 3,612,428
......
1631 7511,790
1632 7514.651
1633 7523,134
1634 7525.508
1635 7549.313
1636 7565.851
1637 7567,741
1638 7569.511

My question is, do I overwrite the cs_lines data with these lines?
or what would be the procedure.

I appreciate any help or guidance you can give me, thank you very much.

**Comment by AWehrhahn** [comment]
The wavelength calibration file (the npz file) should contain a numpy recarray called cs_lines. You can create such a file using ```numpy.savez(filename, cs_lines=data)```.
The recarray should have the fields:

        ((“wlc”, “WLC”), “>f8”), # Wavelength (before fit)
        ((“wll”, “WLL”), “>f8”), # Wavelength (after fit)
        ((“posc”, “POSC”), “>f8”), # Pixel Position (before fit)
        ((“posm”, “POSM”), “>f8”), # Pixel Position (after fit)
        ((“xfirst”, “XFIRST”), “>i2”), # first pixel of the line
        ((“xlast”, “XLAST”), “>i2”), # last pixel of the line
        ((“approx”, “APPROX”), “O”), # ???
        ((“width”, “WIDTH”), “>f8”), # width of the line in pixels
        ((“height”, “HEIGHT”), “>f8”), # relative strength of the line
        ((“order”, “ORDER”), “>i2”), # echelle order the line is found in
        (“flag”, “?”), # flag that tells us if we should use the line or not

**Comment by clrengif** [comment]
Thank you very much for your kind answer, I still have the doubt, if that file should be generated or pyreduce generates it. In case I have to generate it, how should I proceed, what do I need?

**Comment by AWehrhahn** [comment]
The file is used to describe the expected lines and the initial guess for their positions on the detector. As such you have to create it yourself. You will need to determine the wavelength, order, pixel position, width, and height estimates yourself. Although I can recommend the scipy.signal.find_peaks method for that. For the flag just set it to True for all lines.

This code snippet should then create the correct file
```
import numpy as np
from pyreduce.wavelength_calibration import LineList

# Create arrays for wave, order, pos, width, height, flag
# ...

# Create a linelist object, this will force the correct datatype
linedata = LineList.from_list(wave, order, pos, width, height, flag)

# and save it to a file
np.savez(filename, cs_lines=linedata.data)
```
